### ISSUE TITLE
Variable naming 

### ISSUE THREAD

**Issue by pablitoc** [crushlovely/ansible-unicorn-upstart#2]
@pjkelly - Flagging this as an issue to allow us some more time to think about.
 in general, this and the sidekiq roles look good. I have to call into question the variable naming though - these roles are making some general assumptions about how you configure your playbooks (with app_name, app_path, etc.), so I think explanation is warranted in the Readme about why it's setup this way. Thinking more long-term, having a general write-up on your variable strategy across roles and how it all fits together in the context of provisioning an application would be really nice to have.

The alternative here would be changing the variables in these two roles so they're a little more generic. e.g.

```
sidekiq:
  conf_file: [full filename goes here]
  app_path: [full path goes here]
...

unicorn:
  conf_file: [full filename goes here]
  app_path: [full path goes here]
```

Not saying you need to change your approach - just offering food for thought as someone who might want to use this role but doesn't understand the general strategy you're using.
